### ISSUE TITLE
Freeze_tagモードの追加設定看板のhelpの内容が別モード用の設定看板のhelpになっている

### ISSUE THREAD

**Issue by RemiliiaJP** [Ryukkun/bolt#5]
Freeze_tagモードの追加設定(フレンドリーファイヤ,当たり判定)のhelp(看板スニーク右クリック)が
別モードの同座標に出るhelpの内容になっている
例：フレンドリーファイヤ(Freeze_tag) のhelpがScore in tabのhelp(/function lobby:signs/help/options/tab_scoreboard)
環境：
![image](https://github.com/Ryukkun/bolt/assets/105400064/0efd2784-6a7f-4793-9a86-d4b84fad2a11)
![image](https://github.com/Ryukkun/bolt/assets/105400064/88d2762a-f33a-4ed2-96e5-226197b45c4b)
(bolt.f5.siで割と常に開放中)

**Comment by Ryukkun** [comment]
issue作成ありがとうございます！
看板スニーク右クリックにそんな機能が付いていたのですね
後ほど修正します！
