### ISSUE TITLE
矢への効果の設定用看板

### ISSUE THREAD

**Issue by RemiliiaJP** [Ryukkun/bolt#6]
0.0.3から0.0.4に差し替えたときに
看板自体は設置されていたが 3行目の ノーマル 等と出るはずの場所に何も書いておらず 右クリックしても正常に動作しない (1行目は正常ではある)

/scoreboard players set $arrowMode fox_settings 1 にしたあとに看板を再設置させる(loadやendgame)と正常に表示され正常に切り替えられるようになった
/scoreboard players reset $arrowMode fox_settings すると最初の状況に戻った

**Comment by Ryukkun** [comment]
ああ、、、
完全なる初期設定し忘れですね、
