### ISSUE TITLE
ボムのキルログが複数出る事があった

### ISSUE THREAD

**Issue by RemiliiaJP** [Ryukkun/bolt#8]
(0.0.3)ボム自爆の時等に死亡ログが２つ出てた
後で細かく検証するかも

**Comment by RemiliiaJP** [comment]
※人のサーバーでプレイング

**Comment by RemiliiaJP** [comment]
訂正：主にtdmのキルログがおかしい

**Comment by RemiliiaJP** [comment]
眠くてわすれてました
眠いのでわすれるかも

**Comment by Ryukkun** [comment]
> 眠くてわすれてました
> 眠いのでわすれるかも

?

**Comment by Ryukkun** [comment]
@RemiliiaJP ついでに確認一ついいですか？
ボムと地雷のキルログがおかしいのは確認できました！
「主にtdmのキルログがおかしい」とありますが、ボムと地雷以外におかしいログはありますか？

**Comment by RemiliiaJP** [comment]
矢もログ複数出てた時があったかもしれなかった
